// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from example_interfaces/msg/String.msg - do not modify

#include "Msgs/ROS2String.h"

#include "Kismet/GameplayStatics.h"

void UROS2StringMsg::Init()
{
    std_msgs__msg__String__init(&string_msg);
}

void UROS2StringMsg::Fini()
{
    std_msgs__msg__String__fini(&string_msg);
}

const rosidl_message_type_support_t* UROS2StringMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, String);
}

void UROS2StringMsg::SetMsg(const FROSString& Inputs)
{
    Inputs.SetROS2(string_msg);
}

void UROS2StringMsg::GetMsg(FROSString& Outputs) const
{
    Outputs.SetFromROS2(string_msg);
}

void* UROS2StringMsg::Get()
{
    return &string_msg;
}

FString UROS2StringMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
